name: Process CSV

on:
  workflow_dispatch:
    inputs:
      csv_file_path:
        description: 'Path to the CSV file'
        required: true

jobs:
  process-csv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Process CSV file
      run: |
        mkdir -p output
        python process_csv.py "${{ github.event.inputs.csv_file_path }}" "output/completed_data.csv"

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add output/completed_data.csv
        git commit -m 'Add processed CSV file'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


